# Generated by Django 2.0.6 on 2018-06-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
